# Generated by Django 5.0.7 on 2024-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Couse', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='Student_Image/')),
            ],
        ),
    ]
